SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [DATA].[sp__GET_SQL_TABLE_COLUMNS]
(
 @TableName NVARCHAR(MAX)
)
As
BEGIN TRY

    SET NOCOUNT ON;

    SELECT COLUMN_NAME
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = @TableName 
    ORDER BY ORDINAL_POSITION;

END TRY
BEGIN CATCH

  EXECUTE [dbo].[uspLogError];

END CATCH
GO