SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [DATA].[sp__GET_SQL_TABLE_NAME]
As
BEGIN TRY

    SET NOCOUNT ON;

	SELECT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE IN ('BASE TABLE', 'VIEW')
ORDER BY TABLE_SCHEMA, TABLE_NAME;

END TRY
BEGIN CATCH

  EXECUTE [dbo].[uspLogError];

END CATCH
GO