SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAspNetRolesCreate]
@Name nvarchar(256)
AS
BEGIN TRY
	SET NOCOUNT ON;

	INSERT INTO AspNetRoles(Name)
	VALUES (@Name)

	SELECT * FROM AspNetRoles WHERE Name = @Name;
   
END TRY
BEGIN CATCH

  INSERT INTO dbo.DB_Errors
    VALUES (SUSER_SNAME(), ERROR_NUMBER(), ERROR_STATE(), ERROR_SEVERITY(), ERROR_LINE(), ERROR_PROCEDURE(), ERROR_MESSAGE(), GETDATE());

END CATCH
GO