SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spRefreshTokenDelete]
(
	@Original_Id int
)
AS
BEGIN TRY
	SET NOCOUNT OFF;
DELETE FROM [Refresh_Tokens] WHERE (([Id] = @Original_Id))
END TRY
BEGIN CATCH

  INSERT INTO dbo.DB_Errors
    VALUES (SUSER_SNAME(), ERROR_NUMBER(), ERROR_STATE(), ERROR_SEVERITY(), ERROR_LINE(), ERROR_PROCEDURE(), ERROR_MESSAGE(), GETDATE());

END CATCH
GO