SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[spOrgServerListByOrgId]
(
  @Org_Id INT
)
AS
Begin Try
	SET NOCOUNT ON;

	SELECT * FROM OrgServers WHERE OrgServers.Org_Id = @Org_Id

End Try
BEGIN CATCH

  INSERT INTO dbo.DB_Errors
    VALUES (SUSER_SNAME(), ERROR_NUMBER(), ERROR_STATE(), ERROR_SEVERITY(), ERROR_LINE(), ERROR_PROCEDURE(), ERROR_MESSAGE(), GETDATE());

END CATCH
GO