SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spShiftDelete]
(
	@Original_Shift_Id int
)
AS
Begin Try
	SET NOCOUNT OFF;
	DELETE FROM [Shift] WHERE (([Shift_Id] = @Original_Shift_Id))
End Try
BEGIN CATCH

  INSERT INTO dbo.DB_Errors
    VALUES (SUSER_SNAME(), ERROR_NUMBER(), ERROR_STATE(), ERROR_SEVERITY(), ERROR_LINE(), ERROR_PROCEDURE(), ERROR_MESSAGE(), GETDATE());

END CATCH
GO