SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spOrgInfoById]
@Org_Id int
AS
BEGIN TRY
	SET NOCOUNT ON;
     SELECT * FROM OrgInfo WHERE Org_Id = @Org_Id;
END TRY
BEGIN CATCH
  INSERT INTO dbo.DB_Errors
    VALUES (SUSER_SNAME(), ERROR_NUMBER(), ERROR_STATE(), ERROR_SEVERITY(), ERROR_LINE(), ERROR_PROCEDURE(), ERROR_MESSAGE(), GETDATE());

END CATCH
GO