SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spOrgDeptDelete]
(
	@Original_Org_Id int,
	@Original_Dept_Id int
)
AS
BEGIN TRY

DELETE FROM [OrgDept] WHERE (([Org_Id] = @Original_Org_Id) AND ([Dept_Id] = @Original_Dept_Id))

END TRY

BEGIN CATCH

  INSERT INTO dbo.DB_Errors
    VALUES (SUSER_SNAME(), ERROR_NUMBER(), ERROR_STATE(), ERROR_SEVERITY(), ERROR_LINE(), ERROR_PROCEDURE(), ERROR_MESSAGE(), GETDATE());

END CATCH
GO