SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[sp__GET_SQL_TABLE_DATA]
(
 @TableName NVARCHAR(MAX)
)
As
BEGIN TRY

    SET NOCOUNT ON;

	DECLARE @SqlQuery NVARCHAR(MAX);

    SET @SqlQuery = '
        SELECT *
        FROM ' + QUOTENAME(@TableName) + ';';

		 EXEC sp_executesql @SqlQuery;

END TRY
BEGIN CATCH

  INSERT INTO dbo.DB_Errors
    VALUES (SUSER_SNAME(), ERROR_NUMBER(), ERROR_STATE(), ERROR_SEVERITY(), ERROR_LINE(), ERROR_PROCEDURE(), ERROR_MESSAGE(), GETDATE());

END CATCH
GO