SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
Create Proc [dbo].[spDevice_Status_ByDeviceName]
@device NVARCHAR(255)
As
BEGIN TRY
	 SET NOCOUNT ON;

    SELECT id, status
    FROM dbo.device_status
    WHERE device = @device;
END TRY

BEGIN CATCH

  INSERT INTO dbo.DB_Errors
    VALUES (SUSER_SNAME(), ERROR_NUMBER(), ERROR_STATE(), ERROR_SEVERITY(), ERROR_LINE(), ERROR_PROCEDURE(), ERROR_MESSAGE(), GETDATE());

END CATCH
GO