SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAspNetRolesUpdate]
@Id nvarchar(128),
@Name nvarchar(256)
AS
BEGIN TRY
	SET NOCOUNT ON;

	UPDATE AspNetRoles
	SET Name = ISNULL(@Name,Name)
	WHERE Id = @Id

	SELECT * FROM AspNetRoles WHERE Id = @Id
   
END TRY
BEGIN CATCH

  INSERT INTO dbo.DB_Errors
    VALUES (SUSER_SNAME(), ERROR_NUMBER(), ERROR_STATE(), ERROR_SEVERITY(), ERROR_LINE(), ERROR_PROCEDURE(), ERROR_MESSAGE(), GETDATE());

END CATCH
GO