SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [Identity].[spAspNetUserRolesDelete]
@UserId nvarchar(128),
@RoleId nvarchar(128)
AS
BEGIN TRY
	SET NOCOUNT ON;

	DELETE AspNetUserRoles 
	WHERE UserId = @UserId AND RoleId = @RoleId;

	SELECT * FROM AspNetUserRoles WHERE UserId = @UserId;
   
END TRY
BEGIN CATCH

  INSERT INTO dbo.DB_Errors
    VALUES (SUSER_SNAME(), ERROR_NUMBER(), ERROR_STATE(), ERROR_SEVERITY(), ERROR_LINE(), ERROR_PROCEDURE(), ERROR_MESSAGE(), GETDATE());

END CATCH
GO