SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [Identity].[spAspNetUserRolesUpdate]
@UserId nvarchar(128),
@RoleId nvarchar(128)
AS
BEGIN TRY
	SET NOCOUNT ON;

	UPDATE AspNetUserRoles 
	SET UserId = ISNULL(@UserId,UserId),
	    RoleId = ISNUll(@RoleId,RoleId)
	WHERE UserId = @UserId;

	SELECT * FROM AspNetUserRoles WHERE UserId = @UserId;
   
END TRY
BEGIN CATCH

  INSERT INTO dbo.DB_Errors
    VALUES (SUSER_SNAME(), ERROR_NUMBER(), ERROR_STATE(), ERROR_SEVERITY(), ERROR_LINE(), ERROR_PROCEDURE(), ERROR_MESSAGE(), GETDATE());

END CATCH
GO