SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [Project].[spProjectDelete]
(
	@Original_Project_Id int
)
AS
Begin Try
	SET NOCOUNT OFF;
	DELETE FROM [Projects] WHERE (([Project_Id] = @Original_Project_Id))
End Try

BEGIN CATCH

  INSERT INTO dbo.DB_Errors
    VALUES (SUSER_SNAME(), ERROR_NUMBER(), ERROR_STATE(), ERROR_SEVERITY(), ERROR_LINE(), ERROR_PROCEDURE(), ERROR_MESSAGE(), GETDATE());

END CATCH
GO